baseurl = "https://golang.my/"
title = "Golang Malaysia"
copyright = "Copyleft 2016 Malaysian Golang User Group"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = ""

[params]
  name = "Golang Malaysia"
  # role = ""
  # organization = ""
  avatar = "logo.png"
  # email = ""
  # address = ""
  # phone = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Meetups"
    subtitle = ""

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/
  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "https://www.facebook.com/groups/mygolang/"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/golang-my"

# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 3

[[menu.main]]
  name = "Meetups"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Contributing"
  url = "/post/contrib-howto/"
  weight = 9